### ISSUE TITLE
Broken link from part 6 to 7

### ISSUE THREAD

**Issue by Pakillo** [bhaskarvk/user2017.geodataviz#1]
Excellent tutorial! Thanks a lot

There is a broken link in the last slide of part 6 which should take to part 7. Here: https://github.com/bhaskarvk/user2017.geodataviz/blob/master/inst/presentations/06-Static_Maps.Rmd#part-5-the-end

I think it's just missing an underscore, i.e.

`Continue to [Part 7: Interactive Maps](07-Interactive**_**Maps.html)`

**Comment by bhaskarvk** [comment]
Thanks will fix
